cp ~/gpu_workfs/GooFit/src/PDFs/physics/Amp3Body.cu                                       ./Amp3Body.cu
cp ~/gpu_workfs/GooFit/include/goofit/PDFs/physics/Amp3Body.h                             ./Amp3Body.h
cp ~/gpu_workfs/GooFit/src/goofit/FitManagerMinuit2.cpp                                   ./FitManagerMinuit2.cpp
cp ~/gpu_workfs/GooFit/include/goofit/fitting/FitManagerMinuit2.h                         ./FitManagerMinuit2.h
cp ~/gpu_workfs/GooFit/src/PDFs/physics/resonances/LASS.cu                                ./LASS.cu
cp ~/gpu_workfs/GooFit/src/PDFs/physics/resonances/FLATTE.cu                              ./FLATTE.cu
cp ~/gpu_workfs/GooFit/src/PDFs/MetricTaker.cu                                            ./MetricTaker.cu
cp ~/gpu_workfs/GooFit/src/PDFs/GooPdf.cu                                                 ./GooPdf.cu
cp ~/gpu_workfs/GooFit/src/goofit/Params.cpp                                              ./Params.cpp
cp ~/gpu_workfs/GooFit/include/goofit/fitting/Params.h                                    ./Params.h
cp ~/gpu_workfs/GooFit/src/PDFs/physics/resonances/RBW.cu                                 ./RBW.cu
cp ~/gpu_workfs/GooFit/src/PDFs/physics/detail/SpecialResonanceIntegrator.cu              ./SpecialResonanceIntegrator.cu
cp ~/gpu_workfs/GooFit/include/goofit/PDFs/physics/detail/SpecialResonanceIntegrator.h    ./SpecialResonanceIntegrator.h
cp ~/gpu_workfs/GooFit/examples/dalitz/dalitz.cpp                                         ./dalitz.cpp
cp ~/gpu_workfs/GooFit/build/examples/dalitz/dalitz.cpp.withbkg                           ./dalitz.cpp.withbkg
