cp Amp3Body.cu                         ~/gpu_workfs/GooFit/src/PDFs/physics/Amp3Body.cu
cp Amp3Body.h                          ~/gpu_workfs/GooFit/include/goofit/PDFs/physics/Amp3Body.h
cp FitManagerMinuit2.cpp               ~/gpu_workfs/GooFit/src/goofit/FitManagerMinuit2.cpp
cp FitManagerMinuit2.h                 ~/gpu_workfs/GooFit/include/goofit/fitting/FitManagerMinuit2.h
cp LASS.cu                             ~/gpu_workfs/GooFit/src/PDFs/physics/resonances/LASS.cu
cp FLATTE.cu                           ~/gpu_workfs/GooFit/src/PDFs/physics/resonances/FLATTE.cu
cp MetricTaker.cu                      ~/gpu_workfs/GooFit/src/PDFs/MetricTaker.cu
cp GooPdf.cu                           ~/gpu_workfs/GooFit/src/PDFs/GooPdf.cu
cp Params.cpp                          ~/gpu_workfs/GooFit/src/goofit/Params.cpp
cp Params.h                            ~/gpu_workfs/GooFit/include/goofit/fitting/Params.h
cp RBW.cu                              ~/gpu_workfs/GooFit/src/PDFs/physics/resonances/RBW.cu
cp NonResPwave.cu                      ~/gpu_workfs/GooFit/src/PDFs/physics/resonances/NonResPwave.cu
cp NonResPwave.h                       ~/gpu_workfs/GooFit/include/goofit/PDFs/physics/resonances/NonResPwave.h
cp CMakeLists.txt.PDFs.physics         ~/gpu_workfs/GooFit/src/PDFs/physics/CMakeLists.txt
cp SpecialResonanceIntegrator.cu       ~/gpu_workfs/GooFit/src/PDFs/physics/detail/SpecialResonanceIntegrator.cu
cp SpecialResonanceIntegrator.h        ~/gpu_workfs/GooFit/include/goofit/PDFs/physics/detail/SpecialResonanceIntegrator.h
cp dalitz.cpp                          ~/gpu_workfs/GooFit/examples/dalitz/dalitz.cpp
